### ISSUE TITLE
Bring back Ghost Blocks to 1.21

### ISSUE THREAD

**Issue by antirelic11** [CecerMCProjects/NoChangeTheGame#13]
In recent versions you aren't able to create ghost blocks so its quite annoying if you are doing dungeons on Hypixel Skyblock.
However in 1.8.9 (i think even up to 1.18.2) you could still be able to do that.

I don't know if i am clear so here is a video of 2 dudes creating ghost blocks
1st dude https://www.youtube.com/watch?v=6JDMZaeiDvk
2nd dude, shorter video https://www.youtube.com/watch?v=znUbUFsOgIM

Its probably going to be annoying for other players so its best to set this off by default

**Comment by antirelic11** [comment]
i rarely use github, idk if this is the right tab to implement this so please tell me if i should switch tab or not

**Comment by Cecer** [comment]
There is no safe way to unfix this vanilla bug without a high risk of the player getting banned. It's also technically bug abusing in same vein as block glitching so it wouldn't even be a false ban. Sorry :(

(And yeah, you did use this correctly)

**Comment by antirelic11** [comment]
ripp
and alr ty

**Comment by Cecer** [comment]
You can also see #10 for a more detailed reply :)
