### ISSUE TITLE
1.8 Hitboxes

### ISSUE THREAD

**Issue by linsaftw** [CecerMCProjects/NoChangeTheGame#14]
Restore the 1.8 hitboxes to have the same advantages as 1.8 players

**Comment by Mixces** [comment]
I'm pretty sure that can get you banned on Hypixel 🥶

**Comment by Cecer** [comment]
Which hitboxes are you referring to?

**Comment by Mixces** [comment]
> Which hitboxes are you referring to?

I believe he's referring to entity hitboxes. In 1.9+, the hitbox was shortened by 1/10 of a block (hence 0.1)

`Entity#getTargetingMargin()` is the method in question (fabric)

I believe changing this value to match 1.8 could get you banned on Hypixel...

**Comment by Cecer** [comment]
Are you sure? I can't seem to see any difference from my investigation.

**Comment by Mixces** [comment]
> Are you sure? I can't seem to see any difference from my investigation.

Yeah, `Entity#getCollisionBorderSize()` is the equivalent method in 1.8.
![Screenshot (263)](https://github.com/user-attachments/assets/d31582fa-f5d4-4ea1-a1b9-bc53db89eaed) 

This is `Entity#getTargetingMargin()` in 1.21.
![Screenshot (264)](https://github.com/user-attachments/assets/6fdb0115-422b-4c20-9c8e-e8036414f12c)

As the Fabric mapping name suggests, this value is a margin. The collision boxes are technically the same size between 1.8 and 1.21, however, the margin is gone which results in a smaller hit-box.

**Comment by Cecer** [comment]
Ah I think I see how it impacts targets. It is certainly a little roundabout.

While I have doubts that Hypixel would flag it cheating so long as it remains within 1.8 limits, I agree that I don't think it would be appropriate to essentially implement reach, no matter how potentially justifiable, into the mod.

At most I'd consider it an opt-in feature but even then I don't feel happy about it. Not without official approval at very least (and even then I'd still probably want it to be opt-in)

**Comment by linsaftw** [comment]
Thank you guys for opening the discussion about this topic.

I think it's okay, as it is a vanilla feature that players actually have when using a certain version, and it's not really a good thing for 1.8 players to have advantage over others. This will fix it.

If you make it an option (with a warning), I will test it myself and see if there is any problems. It should be fine because Hypixel allows the 1.8 clients and this is just a method to prevent people like me from switching from 1.21 to 1.8 (losing all the performance features) just to be able to compete against other players.

Currently using 1.21 against competitive 1.8 players is unfair gameplay and this would fix this and make it fair for 1.21 players playing in 1.8 servers.

**Comment by Mixces** [comment]
> Thank you guys for opening the discussion about this topic.
> 
> I think it's okay, as it is a vanilla feature that players actually have when using a certain version, and it's not really a good thing for 1.8 players to have advantage over others. This will fix it.
> 
> If you make it an option (with a warning), I will test it myself and see if there is any problems. It should be fine because Hypixel allows the 1.8 clients and this is just a method to prevent people like me from switching from 1.21 to 1.8 (losing all the performance features) just to be able to compete against other players.
> 
> Currently using 1.21 against competitive 1.8 players is unfair gameplay and this would fix this and make it fair for 1.21 players playing in 1.8 servers.

I guess we won't know unless someone tries it 🤣 I'm pretty certain that Watchdog won't like that your 1.21 client is getting hits outside of the normal range and may flag you.

**Comment by Mixces** [comment]
Seemingly, inflating the hit-box to match 1.8 doesn't get me immediately banned on [bedwarspractice.club](https://store.bedwarspractice.club/), however, I'm a bit scared to test the same on Hypixel 🤣

**Comment by Cecer** [comment]
> I think it's okay, as it is a vanilla feature that players actually have when using a certain version, and it's not really a good thing for 1.8 players to have advantage over others. This will fix it.

I don't disagree with you from a moral perspective. However, I don't want to people getting banned for this. I'm not convinced most people would even read a warning either. Even the sneaking hitbox size is on the edge of what I am comfortable and only because it's so situational that it'd have any impact at all.


> It should be fine because Hypixel allows the 1.8 clients

There have been cases where different detection rules are used for different versions. I don't think it is safe to use 1.8 alone as proof that something is safe 


> Currently using 1.21 against competitive 1.8 players is unfair gameplay and this would fix this and make it fair for 1.21 players playing in 1.8 servers.

It might be worth suggesting Hypixel "fix" this on their end with interaction entities of the appropriate size. That would be the safe option and would then be even fairer as it would be the same for everyone playing in at least 1.19.4.

---

The big difference is that pretty much everything else in the mod is purely visual or only impacts the local player in ways that shouldn't even be noticeable but make things feel less buggy. I think that is the scope I'm comfortable with and this feature would not fit within that scope.

**Comment by Mixces** [comment]
For testing purposes, I bit the bullet, and went ahead and inflated the hit-box size to match 1.8. Immediately after entering combat, I got hit with a 30-day ban 🥶

> It might be worth suggesting Hypixel "fix" this on their end with interaction entities of the appropriate size. That would be the safe option and would then be even fairer as it would be the same for everyone playing in at least 1.19.4.

Yep. I think this is only "fair" option. Now we just need to contact a Hypixel admin and ask.

**Comment by Cecer** [comment]
> For testing purposes, I bit the bullet, and went ahead and inflated the hit-box size to match 1.8. Immediately after entering combat, I got hit with a 30-day ban 🥶

o7

**Comment by linsaftw** [comment]
> For testing purposes, I bit the bullet, and went ahead and inflated the hit-box size to match 1.8. Immediately after entering combat, I got hit with a 30-day ban 🥶
> 
> > It might be worth suggesting Hypixel "fix" this on their end with interaction entities of the appropriate size. That would be the safe option and would then be even fairer as it would be the same for everyone playing in at least 1.19.4.
> 
> Yep. I think this is only "fair" option. Now we just need to contact a Hypixel admin and ask.

This can probably be solved by using the ViaVersion mod alongside the hitbox patch. I could test myself if implemented in a dev build or something private.

**Comment by Mixces** [comment]
> > For testing purposes, I bit the bullet, and went ahead and inflated the hit-box size to match 1.8. Immediately after entering combat, I got hit with a 30-day ban 🥶
> > > It might be worth suggesting Hypixel "fix" this on their end with interaction entities of the appropriate size. That would be the safe option and would then be even fairer as it would be the same for everyone playing in at least 1.19.4.
> > 
> > 
> > Yep. I think this is only "fair" option. Now we just need to contact a Hypixel admin and ask.
> 
> This can probably be solved by using the ViaVersion mod alongside the hitbox patch. I could test myself if implemented in a dev build or something private.

The hitbox patch is already in via version actually 🤔

**Comment by Cecer** [comment]
At that point you're opening up a whole different can of worms. (Why are we keeping worms in cans?)

**Comment by linsaftw** [comment]
> > > For testing purposes, I bit the bullet, and went ahead and inflated the hit-box size to match 1.8. Immediately after entering combat, I got hit with a 30-day ban 🥶
> > > > It might be worth suggesting Hypixel "fix" this on their end with interaction entities of the appropriate size. That would be the safe option and would then be even fairer as it would be the same for everyone playing in at least 1.19.4.
> > > 
> > > 
> > > Yep. I think this is only "fair" option. Now we just need to contact a Hypixel admin and ask.
> > 
> > 
> > This can probably be solved by using the ViaVersion mod alongside the hitbox patch. I could test myself if implemented in a dev build or something private.
> 
> The hitbox patch is already in via version actually 🤔

Oh really? Didn't know that. Thanks guys!

**Comment by lowercasebtw** [comment]
ViaFabricPlus is a amazing mod, but I think it already has implemented this and works just fine. I've been using it for months without issue.
