### ISSUE TITLE
1.8 Ladder Breaking Hitbox

### ISSUE THREAD

**Issue by ghost** [CecerMCProjects/NoChangeTheGame#15]
The ladder breaking hitbox got changed in 1.9 which makes farms like the one I have built not work, since the 3rd melon is not breakable while using the optimal Pitch.

![image](https://github.com/user-attachments/assets/08294c06-7926-478f-9ce6-a5320ee1e589)
![image](https://github.com/user-attachments/assets/0c626d9e-b72b-4197-a3b3-4b52b8862949)

Would be nice to have an option to revert back to 1.8 ladder breaking hitboxes similar to the option Patcher has in 1.8.9 to make crop hitboxes 1.12.2 ones.

**Comment by Cecer** [comment]
I'm quite concerned about changing the hitbox of anything. Even the player sneak hitbox is not something I'm super comfortable with. As Hypixel adds more and more modern functionality to the server, changes like this are more likely to be detected. At most, an opt in feature might be something to consider.

**Comment by ghost** [comment]
Understandable, thank you for the consideration.

**Comment by Cecer** [comment]
I've decided to close "risky" suggestions. I might revisit them in the future but it's important to me to not get anyone banned by using the official features of this mod.

**Comment by lowercasebtw** [comment]
Hypixel allows people to backport the 1.12 crop hitboxes & other stuff, why can't we forward port this? I don't think it will cause issues, should be fine.
