### ISSUE TITLE
Fix armor stand rendering on newer versions

### ISSUE THREAD

**Issue by IllagerCaptain** [CecerMCProjects/NoChangeTheGame#22]
Basically furniture, pets, and other decoration appear wrong in 1.21. In 1.8, this pet would be facing me and aligned with the nametag and particles. Note: It's the pet model that's offset, the nametag and particles are at the correct position.
![](https://github.com/user-attachments/assets/55a4f5ce-0b15-4e48-bcf9-ca57a3e8d337)

**Comment by Cecer** [comment]
This is much more complicated to fix sadly as Hypixel already does some partial fixing that would conflict. It would also break all other armor stand art.
