### ISSUE TITLE
Update to 1.20.6?

### ISSUE THREAD

**Issue by Vricken** [CecerMCProjects/NoChangeTheGame#3]
Just discovered the mod, looks interesting. Could you update it to 1.20.6?

**Comment by Cecer** [comment]
I'll see if I can find the time this week 🙂

**Comment by Cecer** [comment]
v1.0.2 is now out with support for 1.20.5 and 1.20.6.

You can download it from the [Modrinth project](https://modrinth.com/mod/nochangethegame/version/1.0.2) or the [GitHub release page](https://github.com/CecerMCProjects/NoChangeTheGame/releases/v1.0.2).
