### ISSUE TITLE
Invisible Shield makes SkyBlock worse 

### ISSUE THREAD

**Issue by Fluboxer** [CecerMCProjects/NoChangeTheGame#8]
Ima be short. There is Hypixel. There is SkyBlock at Hypixel. There are tools at Hypixel that DOES NOT slow you down or have shield at all. However, enabling invisible shield enables it even for weapons that should **not** have it 
Disabling invisible shield option fixes that obviously, but you lose on invisible shields 

Current things I found that should NOT have invisible shield: all wither blades with ability "Wither Impact", all katanas ([this](https://wiki.hypixel.net/Voidedge_Katana) one and it's upgrades), aspect of the end. There may be more

**Comment by Cecer** [comment]
There isn't really a way to automate this but I can likely just have a list of SkyBlock item IDs that don't handle blocking. I assume this issue isn't specific to this mod but also impacts pre-1.9 versions?

**Comment by Fluboxer** [comment]
On 1.8 those items do block, yes, as they are all swords. Not having it is one of very few reasons why people were getting modern versions before skyblocker got big 

I can go and collect items tho for wither impact you need to either check components for it or description as telling apart clean hyperion from one with wither impact from id.... I doubt that this is easily doable

**Comment by Cecer** [comment]
When you have time, would it be possible for you to show me these items so I can collect some technical values from them?

**Comment by Fluboxer** [comment]
ofc

I can also just go to 1.20.4 where there are proper mods capable of dumping NBT and just give you dumps of it

**Comment by Fluboxer** [comment]
actually ima do it anyway. Those are NBT dumps from 1.20.4:
[aspect of the end.txt](https://github.com/user-attachments/files/15803241/aspect.of.the.end.txt)
[atomsplit katana.txt](https://github.com/user-attachments/files/15803242/atomsplit.katana.txt)
[wither impact Astraea.txt](https://github.com/user-attachments/files/15803243/wither.impact.Astraea.txt)

**Comment by Cecer** [comment]
Thanks! The structure of item data changed in 1.20.5 but I think I've been able to make it work. Are there other items that don't show a shield when blocking?

I currently check for "ASPECT_OF_THE_END", "VOIDEDGE_KATANA", "ATOMSPLIT_KATANA" and Wither Impact (which I believe is just the combination of "WITHER_SHIELD_SCROLL" + "IMPLOSION_SCROLL" + "SHADOW_WARP_SCROLL" ability scrolls based on the wiki)

**Comment by Fluboxer** [comment]
Also VORPAL_KATANA

Ima go post this in skyblocker discord in case we both forgor anything

upd:
![изображение](https://github.com/CecerMCProjects/NoChangeTheGame/assets/36457056/87c36dcd-e5de-4018-b3bf-917a91720491)

**Comment by lunaynx** [comment]
Yeah, why not just disable blocking for any sword item while on SkyBlock?

**Comment by Cecer** [comment]
I'd really prefer to keep the blocking exception to places where the server also has an exception.

I have gone through the wiki and come up with this list of unblockable sword items. Do any of these look out of place? Can you think of any that are missing?
(Checked items have been verified to be unblockable in modern versions)
- [x] [ASPECT_OF_THE_DRAGON](https://wiki.hypixel.net/ASPECT_OF_THE_DRAGON)
- [x] [ASPECT_OF_THE_END](https://wiki.hypixel.net/ASPECT_OF_THE_END)
- [x] [ASPECT_OF_THE_JERRY](https://wiki.hypixel.net/ASPECT_OF_THE_JERRY)
- [x] [ASPECT_OF_THE_JERRY_SIGNATURE](https://wiki.hypixel.net/ASPECT_OF_THE_JERRY_SIGNATURE)
- [x] [ATOMSPLIT_KATANA](https://wiki.hypixel.net/ATOMSPLIT_KATANA)
- [ ] [~~BLADE_OF_DRAGONFIRE~~](https://wiki.hypixel.net/BLADE_OF_DRAGONFIRE) (unobtainable)
- [ ] [BONE_REAVER](https://wiki.hypixel.net/BONE_REAVER)
- [x] [BURSTFIRE_DAGGER](https://wiki.hypixel.net/BURSTFIRE_DAGGER)
- [x] [BURSTMAW_DAGGER](https://wiki.hypixel.net/BURSTMAW_DAGGER)
- [x] [CRYPT_DREADLORD_SWORD](https://wiki.hypixel.net/CRYPT_DREADLORD_SWORD)
- [x] [EARTH_SHARD](https://wiki.hypixel.net/EARTH_SHARD)
- [x] [END_STONE_SWORD](https://wiki.hypixel.net/END_STONE_SWORD)
- [ ] [FELTHORN_REAPER](https://wiki.hypixel.net/FELTHORN_REAPER) (untested)
- [x] [FIREDUST_DAGGER](https://wiki.hypixel.net/FIREDUST_DAGGER)
- [x] [FLORID_ZOMBIE_SWORD](https://wiki.hypixel.net/FLORID_ZOMBIE_SWORD)
- [ ] [~GIANTS_EYE_SWORD~](https://wiki.hypixel.net/GIANTS_EYE_SWORD) (unobtainable)
- [ ] [_GIANTS_SWORD_](https://wiki.hypixel.net/GIANTS_SWORD) (untested)
- [x] [GOLEM_SWORD](https://wiki.hypixel.net/GOLEM_SWORD)
- [x] [HEARTFIRE_DAGGER](https://wiki.hypixel.net/HEARTFIRE_DAGGER)
- [x] [HEARTMAW_DAGGER](https://wiki.hypixel.net/HEARTMAW_DAGGER)
- [ ] [LEAPING_SWORD](https://wiki.hypixel.net/LEAPING_SWORD)
- [x] [LIVID_DAGGER](https://wiki.hypixel.net/LIVID_DAGGER)
- [x] [MAWDUST_DAGGER](https://wiki.hypixel.net/MAWDUST_DAGGER)
- [x] [NECROMANCER_SWORD](https://wiki.hypixel.net/NECROMANCER_SWORD)
- [x] [ORNATE_ZOMBIE_SWORD](https://wiki.hypixel.net/ORNATE_ZOMBIE_SWORD)
- [x] [PIGMAN_SWORD](https://wiki.hypixel.net/PIGMAN_SWORD)
- [X] [ROGUE_SWORD](https://wiki.hypixel.net/ROGUE_SWORD)
- [ ] [_SHADOW_FURY_](https://wiki.hypixel.net/SHADOW_FURY) (untested)
- [x] [SILENT_DEATH](https://wiki.hypixel.net/SILENT_DEATH)
- [ ] [SILK_EDGE_SWORD](https://wiki.hypixel.net/SILK_EDGE_SWORD)
- [x] [SPIRIT_SWORD](https://wiki.hypixel.net/SPIRIT_SWORD)
- [ ] [_STARRED_SHADOW_FURY_](https://wiki.hypixel.net/STARRED_SHADOW_FURY) (untested)
- [ ] [_STARRED_YETI_SWORD_](https://wiki.hypixel.net/STARRED_YETI_SWORD) (untested)
- [x] [SWORD_OF_BAD_HEALTH](https://wiki.hypixel.net/SWORD_OF_BAD_HEALTH)
- [x] [VORPAL_KATANA](https://wiki.hypixel.net/VORPAL_KATANA)
- [x] [WITHER_CLOAK](https://wiki.hypixel.net/WITHER_CLOAK)
- [ ] [_YETI_SWORD_](https://wiki.hypixel.net/YETI_SWORD) (untested)
- [x] [ZOMBIE_SWORD](https://wiki.hypixel.net/ZOMBIE_SWORD)

**Comment by lunaynx** [comment]
I'm pretty sure sword blocking has never done anything on SkyBlock. It may work visually on older clients because the server can't exactly stop it, but it has practically zero effect.

**Comment by Cecer** [comment]
The shield style blocking still shows for standard swords on modern versions. I found a Rogue Sword on a very old coop profile and confirmed that it does not show the shield style blocking when right clicking. So it is certainly handled as a special case on the items rather than the game as a whole.

**Comment by Fluboxer** [comment]
I'm busy next few days but I after that I can go and check this list 

criteria is shield appearing?

**Comment by Cecer** [comment]
Yep! If the shield appears in modern vanilla, that means the server considers the player to be blocking. The closer we match what the server is expecting the better in my opinion.

Thanks for your help with this by the way. It's obviously not something I can easily test given I don't play SkyBlock :P

**Comment by lunaynx** [comment]
My bad, I didn't realize Hypixel actually implemented the shield thing for swords without abilities in SkyBlock. A bit surprising, because I've never seen sword blocking ever be useful in the game, but it makes sense to follow that then.

I can confirm the shield does not appear for:
* `ASPECT_OF_THE_DRAGONS`
* `ASPECT_OF_THE_END`
* `ASPECT_OF_THE_JERRY`
* `CRYPT_DREADLORD_SWORD`
* `EARTH_SHARD`
* `SPIRIT_SWORD`

It *does* appear for the following items, whose abilities aren't right-click:
* `HYPER_CLEAVER`
* `SUPER_CLEAVER`

**Comment by lunaynx** [comment]
Also confirmed to have no shield:
* `END_STONE_SWORD`
* `PIGMAN_SWORD`
* `SILENT_DEATH`
* `SWORD_OF_BAD_HEALTH`

**Comment by Cecer** [comment]
FYI: I've removed `GIANT_CLEAVER` too as I believe it falls into the same category of `HYPER_CLEAVER` and `SUPER_CLEAVER`.

**Comment by Fluboxer** [comment]
[ATOMSPLIT_KATANA](https://wiki.hypixel.net/ATOMSPLIT_KATANA) - no shield. Also should have no shield on other katanas I listed
[FLORID_ZOMBIE_SWORD](https://wiki.hypixel.net/FLORID_ZOMBIE_SWORD) - no shield (which buffs it a lot for burst healing). Also should have no shield on lesser versions of itself
[GOLEM_SWORD](https://wiki.hypixel.net/GOLEM_SWORD) - no shield. Can't be spammed 
https://wiki.hypixel.net/Blade_Of_Dragonfire - does not exist 
[GIANTS_EYE_SWORD](https://wiki.hypixel.net/GIANTS_EYE_SWORD) - unobtainable (does not exist)
[LIVID_DAGGER](https://wiki.hypixel.net/LIVID_DAGGER) - no shield. Can't be spammed 
Also for whole 6 entries for both blaze slayer daggers - those should have no shield either. I tested it on twilight dagger - daggers are same-ish in terms of ability and they all upgrades of each other

**Comment by Fluboxer** [comment]
I lack Giant's Sword and Shadow Fury to test tho

**Comment by Cecer** [comment]
I've marked the following as unobtainable in the list above. I'll probably leave them as "no-shield" items in the mod for the time being though.
- `BLADE_OF_DRAGONFIRE`
- `GIANTS_EYE_SWORD`

I've marked the following items as verfied in the list above.
- `ATOMSPLIT_KATANA`
- `VORPAL_KATANA`
- `FLORID_ZOMBIE_SWORD`
- `ORNATE_ZOMBIE_SWORD`
- `ZOMBIE_SWORD`
- `GOLEM_SWORD`
- `BURSTFIRE_DAGGER`
- `BURSTMAW_DAGGER`
- `FIREDUST_DAGGER`
- `HEARTFIRE_DAGGER`
- `HEARTMAW_DAGGER`
- `LIVID_DAGGER`
- `MAWDUST_DAGGER`

I've marked the following as untested in the list above.
- `GIANTS_SWORD`
- `SHADOW_FURY`
- `STARRED_SHADOW_FURY`

Any issues these changes?

**Comment by Fluboxer** [comment]
STARRED_SHADOW_FURY and SHADOW_FURY are same thing. Same goes for yeti sword
[FELTHORN_REAPER](https://wiki.hypixel.net/FELTHORN_REAPER) is [BONE_REAVER](https://wiki.hypixel.net/BONE_REAVER) upgrade
[ASPECT_OF_THE_JERRY_SIGNATURE](https://wiki.hypixel.net/ASPECT_OF_THE_JERRY_SIGNATURE) is same as AOTJ (just 1 rarity up + cursed enchant) and it probably have no shield if AOTJ don't

ima test [NECROMANCER_SWORD](https://wiki.hypixel.net/NECROMANCER_SWORD), [WITHER_CLOAK](https://wiki.hypixel.net/WITHER_CLOAK), [LEAPING_SWORD](https://wiki.hypixel.net/LEAPING_SWORD) and [SCORPION_FOIL](https://wiki.hypixel.net/SCORPION_FOIL) later

**Comment by Cecer** [comment]
While essentially the same thing, the wiki states they have different SkyBlock item IDs which is what I am checking against so I added them both to the list. Thank for all the testing by the way!

**Comment by Fluboxer** [comment]
Necromancer Sword - no shield 
Wither Cloak - no shield 
Leaping Sword and Silk Edge Sword - no shield 
Scorpion Foil - DOES HAVE SHIELD. In fact it is a part of its mecanic. I would be quite amused as it is unique thing - if this sword wouldn't be useless

iirc we lack SF, Felthorn, Giant's and Yeti (and their family)


_also 1.21 is out and so most mods, including skyblock ones_

**Comment by Cecer** [comment]
Thanks :) I've made note of those results. As for 1.21, it's on my radar. I'd like to get this and #5 in for it too. Time has just been a little tighter recently.

**Comment by Cecer** [comment]
I'm happy to assume the rest of the swords in the list should not block based on their wiki descriptions. This should be part of v1.1.0 (for Minecraft 1.21).

Thanks very much for your help with this!

**Comment by Cecer** [comment]
Release Candidate: https://github.com/CecerMCProjects/NoChangeTheGame/releases/tag/v1.1.0-rc3
(I'll probably release tomorrow)
